### ISSUE TITLE
Feedback on second submission

### ISSUE THREAD

**Issue by Anisha7** [sadboykj/telio#2]
Good job on completing the second coding challenge. Here's some feedback to improve your code further:
- the top of your ArrayStack needs to be n-1 for full credit. This optimization is necessary because inserting and popping from index 0 of a list is very costly. At each iteration, the list has to move all of its elements to the left if removed from index 0, and to the right when inserted at 0. Inserting and removing from the end is O(1)

**Comment by kjwilsondev** [comment]
thanks for the feedback ! I went ahead and optimized my Array Stack !!
