### ISSUE TITLE
Feedback: Call Routing Project

### ISSUE THREAD

**Issue by Anisha7** [sadboykj/telio#5]
- You benchmarked time complexity for only one of the solutions. Do this for both solutions for the extra point. In addition, this will allow you to compare which solution works better! 
- I cannot find scenario 4 and scenario 5 implementations. Talk about your these two implementations and how to run/test them in your README.

**Comment by kjwilsondev** [comment]
Thanks Anisha - I went ahead and added benchmarked v1. Then I added documentation for scenario 4 & 5 in the readme as well as in the tests. I output the number costs in a text file for Scenario 4, and implemented an update_routes function for scenario 5
